on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy_portfolio:
    name: Deploy IaC portfolio
    runs-on: ${{ matrix.os }}
    steps:
      - name: CDK Deploy step
      - run: cdk deploy
      
